services:
  - type: web
    name: sentiment-analysis-lstm
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3